version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-1-31-0"
exclude_patterns:
  - ".codeclimate.yml"
  - ".circleci/"
  - ".gitignore"
  - ".rspec"
  - ".rubocop.yml"
  - ".ruby-gemset"
  - ".ruby-version"
  - "app/assets/"
  - "app/admin/"
  - "bin/"
  - "config/"
  - "config.ru"
  - "cirle.yml"
  - "db/"
  - "features/"
  - "Gemfile"
  - "Gemfile.lock"
  - "Guardfile"
  - "public/"
  - "Rakefile"
  - "resources/"
  - "README.rdoc"
  - "routes.txt"
  - "ruby-gemset"
  - "spec/"
  - "spec/magic_lamp.rb"
  - "spec/magic_lamp_config.rb"
  - "script/"
  - "test/"
  - "tmp/"
  - "vendor/"

Rubocop/Style/RegexpLiteral:
  enabled: false
Rubocop/Layout/EmptyLinesAroundModuleBody:
  enabled: false
Rubocop/Layout/EmptyLinesAroundMethodBody:
  enabled: false
Rubocop/Layout/EmptyLinesAroundBlockBody:
  enabled: false
Rubocop/Style/SymbolArray:
  enabled: false
Rubocop/Layout/EmptyLines:
  enabled: false
Rubocop/Layout/TrailingWhitespace:
  enabled: false
Rubocop/Layout/IndentHash:
  enabled: false
Rubocop/Layout/MultilineMethodCallIndentation:
  enabled: false
Rubocop/Style/WordArray:
  enabled: false
Rubocop/Layout/EmptyLinesAroundExceptionHandlingKeywords:
  enabled: false
Rubocop/Layout/TrailingBlankLines:
  enabled: false
