require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'

# Rails rules
Rails/ResponseParsedBody:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

# Style rules
Style/OptionalBooleanParameter:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'app/admin/**/*'

Style/MultilineIfModifier:
  Exclude:
    - 'app/admin/**/*'

# Layout rules
Layout/HashAlignment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/LineLength:
  Max: 125
  Exclude:
    - '**/*_spec.rb'
    - '**/factories/**.rb'
    - 'Gemfile'
    - 'config/**/*.rb'
    - 'app/admin/**/*.rb'

# Metrics rules
Metrics/AbcSize:
  Exclude:
    - '**/*_spec.rb'

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - '**/*_spec.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '**/factories/**.rb'
    - 'config/**/*.rb'
    - 'lib/tasks/**'
    - 'app/admin/**/*.rb'

# Lint rules
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
