require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'

# Rails rules
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/ResponseParsedBody:
  Enabled: false

Rails/Pluck:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/MailerName:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

# Style rules
Style/GlobalStdStream:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'app/admin/**/*'

Style/MultilineIfModifier:
  Exclude:
    - 'app/admin/**/*'

# Layout rules
Layout/HashAlignment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/LineLength:
  Max: 140
  Exclude:
    - '**/*_spec.rb'
    - '**/factories/**.rb'
    - 'Gemfile'
    - 'config/**/*.rb'
    - 'app/admin/**/*.rb'

# Metrics rules
Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '**/factories/**.rb'
    - 'config/**.rb'
    - 'config/environments/**.rb'
    - 'lib/tasks/**'
    - 'app/admin/**/*.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

# Lint rules
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

# Naming rules
Naming/VariableNumber:
  Enabled: false
