export const ALL_STEPS = [
    {id:"1", step:"emotion-selection-web"},
    {id:"1.1.", step:"emotion-entry"},
    {id:"2.0", step: "meme-selection"},
    {id:"2.25", step:"selected-giphy-follow"},
    {id:"3.1.", step:"emotion-intensity"},
    {id:"4.1.", step:"productivity-check"},
    {id:"4.25.", step:"ProductivityBadFollowUp"},
    {id:"5", step:"CausesToCelebrate"},
    {id:"6", step:"ShoutoutPromptNone"},
    {id:"6.X.", step:"ShoutoutModalExample"},
    {id:"6.XX", step:"ShoutoutModal_FlexUse"},
    {id:"7v2", step:"Icebreaker"},
    {id:"7", step:"results"},
    {id:"7.1.", step:"MemeWallPrevWeek"},
    {id:"7.3.", step:"MemeWallThisWeek"},
    {id:"7.X.1.", step:"MemeWallThisWeekSoFarDrop"},
    {id:"8", step:"PromptEmailResults"},
  ];